version: "3.3"

services:
  shared-configuration:
    build:
      context: ./config
    volumes:
      - shared-config:/config

  scalyr:
    image: openlmis/scalyr:${OL_SCALYR_AGENT_VERSION}
    volumes:
      - shared-config:/config
      - ${SCALYR_DOCKER_SOCK}:/var/scalyr/docker.sock
      - syslog:/var/log/nifi-registry
    env_file: settings.env
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}

  log:
    image: openlmis/rsyslog:${OL_RSYSLOG_VERSION}
    volumes:
      - syslog:/var/log
    ports:
      - "${SYSLOG_UDP_PORT}:514/udp"

  nifi-registry:
    image: apache/nifi-registry:${OL_NIFI_REGISTRY_VERSION}
    ports:
      - "${NIFI_REGISTRY_HTTP_PORT}:18080"
      - "${NIFI_REGISTRY_HTTPS_PORT}:18443"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:${SYSLOG_UDP_PORT}"
    depends_on: [log]

volumes:
  syslog:
    external: false
  shared-config:
    external: false
