version: "3.3"

services:
  shared-configuration:
    build:
      context: ./config
    volumes:
      - shared-config:/config

  backup:
    build:
      context: ./s3-backup
    volumes:
      - registry-database:${BACKUP_DIRECTORY}/nifi-registry-database
      - flow-storage:${BACKUP_DIRECTORY}/nifi-registry-persistence
    env_file: settings.env
    environment:
      BACKUP_CRON_SCHEDULE: ${BACKUP_CRON_SCHEDULE}
      BACKUP_DIRECTORY: ${BACKUP_DIRECTORY}
  scalyr:
    image: openlmis/scalyr:${OL_SCALYR_AGENT_VERSION}
    volumes:
      - shared-config:/config
      - ${SCALYR_DOCKER_SOCK}:/var/scalyr/docker.sock
      - syslog:/var/log/nifi-registry
    env_file: settings.env
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}

  log:
    image: openlmis/rsyslog:${OL_RSYSLOG_VERSION}
    volumes:
      - syslog:/var/log
    ports:
      - "${SYSLOG_UDP_PORT}:514/udp"

  nifi-registry:
    image: apache/nifi-registry:${OL_NIFI_REGISTRY_VERSION}
    ports:
      - "${NIFI_REGISTRY_HTTP_PORT}:18080"
      - "${NIFI_REGISTRY_HTTPS_PORT}:18443"
    volumes:
      - flow-storage:/opt/nifi-registry/nifi-registry-${OL_NIFI_REGISTRY_VERSION}/flow_storage:rw
      - registry-database:/opt/nifi-registry/nifi-registry-${OL_NIFI_REGISTRY_VERSION}/database:rw
      - shared-config:/config
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:${SYSLOG_UDP_PORT}"
    depends_on: [log, backup, shared-configuration]

volumes:
  syslog:
    external: false
  shared-config:
    external: false
  registry-database:
    external: false
  flow-storage:
    external: false

