version: "3.3"

services:
  scalyr:
    image: scalyr/scalyr-docker-agent:${OL_SCALYR_AGENT_VERSION}
    volumes:
      - ./config/scalyr/agent.d:/etc/scalyr-agent-2/agent.d
      - ${SCALYR_DOCKER_SOCK}:/var/scalyr/docker.sock
      - syslog:/var/log
    environment:
      - SCALYR_API_KEY=${SCALYR_API_KEY}
      - SCALYR_HOSTNAME=${SCALYR_HOSTNAME}

  log:
    image: openlmis/rsyslog:${OL_RSYSLOG_VERSION}
    volumes:
      - syslog:/var/log
      - ./config/rsyslog/rsyslog.d:/etc/rsyslog.d
    ports:
      - "${SYSLOG_UDP_PORT}:514/udp"

  nifi-registry:
    image: apache/nifi-registry:${OL_NIFI_REGISTRY_VERSION}
    ports:
      - "${NIFI_REGISTRY_HTTP_PORT}:18080"
      - "${NIFI_REGISTRY_HTTPS_PORT}:18443"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:${SYSLOG_UDP_PORT}"
    depends_on: [log]

volumes:
  syslog:
    external: false
