version: "3.3"
services:

  config-container:
    build:
      context: ./config
    volumes:
      - config-volume:/config
      - telegraf-config-volume:/config/telegraf

  influxdb:
    image: influxdb:${OL_INFLUXDB_VERSION}
    ports:
      - 8086:8086
    volumes:
      - influxdb-volume:/var/lib/influxdb

  telegraf:
    image: telegraf:${OL_TELEGRAF_VERSION}
    volumes:
      - telegraf-config-volume:/etc/telegraf
    depends_on: [influxdb]

  grafana:
    image: grafana/grafana:${OL_GRAFANA_VERSION}
    ports:
      - 3000:3000
    volumes:
      - config-volume:/config
    environment:
      - GF_PATHS_PROVISIONING=/config/grafana/provisioning

volumes:
  config-volume:
    external: false
  telegraf-config-volume:
    external: false
  influxdb-volume:
    external: false
