# config file version
apiVersion: 1

datasources:
- id: 2
  orgId: 1
  name: InfluxDB
  type: influxdb
  typeLogoUrl: public/app/plugins/datasource/influxdb/img/influxdb_logo.svg
  access: proxy
  url: http://influxdb:8086
  password: ''
  user: ''
  database: telegraf
  basicAuth: false
  isDefault: false
  jsonData:
    httpMode: GET
    keepCookies: []
  readOnly: false
