---
- name: Install dependencies from APT
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - awscli
    - python-openssl
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2

- include_tasks: install-postgresql-extensions.yml
  when: use_rds is defined
